// d1_mini_relay.ino — LOLIN D1 mini Pro (ESP8266EX) WiFi client + serial relay for SONY Spresense.
// v2: robust init — no ESP.wdtDisable, no WiFi auto-reconnect surprise, slower WiFi bootstrap.
//
// Link to Spresense (revised 2026-08-21 — GPIO1/UART0-TX is CH340-clamped, unusable):
//   Status/data TX:  Serial1 (TX-only, GPIO2)      @115200  -> Spresense Serial2 RX (D00)
//   CONFIG/DATA_RX: Serial  (UART0 RX, GPIO3)      @115200  <- Spresense Serial2 TX (D01)
// Debug output:      Serial  (UART0 TX, GPIO1)     @115200  -> COM15 (bench, D1 on USB only)
//
// WiFi credentials come from the Spresense via CONFIG frame (preferred). For isolated
// bench testing where the Spresense is not connected, build with -DTEST_DIRECT_WIFI to
// use build-time TEST_SSID / TEST_PASS / TEST_SERVER_URL. Secrets are NEVER committed —
// the production build (no -DTEST_DIRECT_WIFI) contains no hardcoded credentials.
//
// FQBN: esp8266:esp8266:d1_mini:xtal=80,eesz=4M1M,ip=lm2f,baud=115200

#include <ESP8266WiFi.h>
#include <ESP8266HTTPClient.h>
#include <WiFiClient.h>
#include "relay_proto.h"

// Link roles (revised 2026-08-21 — see memory relay-link-diagnosis):
//   Status/data TX  -> Serial1 (TX-only, GPIO2) -> Spresense D00 (UART2 RX).
//     GPIO1/UART0-TX is unusable for the link: the on-board CH340 clamps it
//     to a 0.7-1.8 V swing when the CH340 is unpowered (D1 on a charger), below
//     the Spresense D00 VIH. GPIO2 is not shared with the CH340 -> clean swing.
//   CONFIG/DATA_UP RX <- Serial   (UART0 RX, GPIO3) <- Spresense D01 (UART2 TX).
//   Debug output      -> Serial   (UART0 TX, GPIO1) -> COM15 when D1 is on USB
//     (bench only; clamped/unreadable when on a charger, but nothing listens).
#define DBG(x)   Serial.print(x)
#define DBGln(x) Serial.println(x)

// ----- TEST_DIRECT_WIFI: build-time fallback (NEVER committed with real values) -----
// Credentials come from d1_mini_relay/test_creds.h, generated by
// tools/gen_test_creds.py from the local ~/.d1_test_pass file. Passing string
// macros on the command line (-DTEST_SSID="x") is unreliable on Windows /
// PowerShell + arduino-cli (the quotes get stripped before reaching gcc), so
// the header is the supported path. __has_include keeps the build working
// when the header is absent (just with empty creds -> WiFi test skips).
#ifdef TEST_DIRECT_WIFI
  #if __has_include("test_creds.h")
    #include "test_creds.h"
  #endif
  #ifndef TEST_SSID
    #define TEST_SSID ""
  #endif
  #ifndef TEST_PASS
    #define TEST_PASS ""
  #endif
  #ifndef TEST_SERVER_URL
    #define TEST_SERVER_URL ""
  #endif
#endif

// ----- State -----
Parser spParser;
String cfgSsid, cfgPass, cfgServerUrl;
bool wifiReady = false;
bool configReceived = false;
unsigned long lastPing = 0;
unsigned long lastHeartbeat = 0;
unsigned long lastSelfPost = 0;

void connectWifi() {
  DBG(F("WiFi begin: ")); DBGln(cfgSsid);
  // Gentle bootstrap: OFF -> STATION with a small delay in between.
  WiFi.persistent(false);
  WiFi.mode(WIFI_OFF);
  delay(100);
  WiFi.mode(WIFI_STA);
  delay(100);
  WiFi.begin(cfgSsid.c_str(), cfgPass.c_str());

  unsigned long t0 = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - t0 < 15000) {
    delay(250);
    yield();
  }
  if (WiFi.status() == WL_CONNECTED) {
    wifiReady = true;
    DBG(F("WiFi OK IP=")); DBGln(WiFi.localIP().toString());
    sendFrameStr(Serial1,T_STATUS, String("IP=") + WiFi.localIP().toString());
  } else {
    wifiReady = false;
    DBGln(F("WiFi FAIL"));
    sendFrameStr(Serial1,T_STATUS, "WiFi_FAIL");
  }
}

void onFrame(uint8_t type, const uint8_t *payload, size_t len) {
  String s = "";
  for (size_t i = 0; i < len; i++) s += (char)payload[i];
  switch (type) {
    case T_CONFIG: {
      cfgSsid = jsonField(s, "ssid");
      cfgPass = jsonField(s, "pass");
      cfgServerUrl = jsonField(s, "server_url");
      configReceived = true;
      DBG(F("CONFIG ssid=")); DBG(cfgSsid); DBG(F(" srv=")); DBGln(cfgServerUrl);
      connectWifi();
      break;
    }
    case T_DATA_UP: {
      if (!wifiReady || cfgServerUrl.length() == 0) {
        sendFrameStr(Serial1,T_DATA_DOWN, "NO_WIFI_OR_SERVER");
        break;
      }
      WiFiClient client;
      HTTPClient http;
      http.setTimeout(8000);
      if (http.begin(client, cfgServerUrl)) {
        http.addHeader("Content-Type", "application/octet-stream");
        int code = http.POST((uint8_t *)payload, len);
        String resp = (code > 0) ? http.getString() : String("HTTP_ERR_") + code;
        http.end();
        sendFrameStr(Serial1,T_DATA_DOWN, resp);
        DBG(F("POST -> ")); DBG(code); DBG(F(" ")); DBGln(resp);
      } else {
        sendFrameStr(Serial1,T_DATA_DOWN, "HTTP_BEGIN_FAIL");
      }
      break;
    }
    case T_PING:
      sendFrameStr(Serial1,T_PONG, "");
      break;
    default:
      DBG(F("Unknown frame type=0x")); DBGln(String(type, HEX));
      break;
  }
}

void setup() {
  Serial.begin(115200);   // UART0: RX=GPIO3 (CONFIG from Spresense D01), TX=GPIO1 (debug, bench only)
  Serial1.begin(115200);  // UART1 TX=GPIO2 -> Spresense D00 (status/data frames to Spresense)
  delay(200);
  parserReset(spParser);
  DBGln(F("D1 mini Pro (ESP8266EX) relay v2 boot"));
  sendFrameStr(Serial1,T_STATUS, "BOOT_WAITING_CONFIG");

#ifdef TEST_DIRECT_WIFI
  // Isolated bench mode: if no CONFIG in 8s, use build-time credentials.
  if (strlen(TEST_SSID) > 0) {
    unsigned long t0 = millis();
    while (!configReceived && millis() - t0 < 8000) {
      while (Serial.available()) {
        uint8_t b = Serial.read();
        if (parseByte(spParser, b)) onFrame(spParser.type, spParser.buf, spParser.len);
      }
      delay(20);
    }
    if (!configReceived) {
      DBGln(F("TEST_DIRECT_WIFI: no CONFIG, using build-time credentials"));
      cfgSsid = TEST_SSID;
      cfgPass = TEST_PASS;
      cfgServerUrl = TEST_SERVER_URL;
      configReceived = true;
      connectWifi();
    }
  }
#endif
}

void loop() {
  while (Serial.available()) {
    uint8_t b = Serial.read();
    if (parseByte(spParser, b)) onFrame(spParser.type, spParser.buf, spParser.len);
  }

#ifdef TEST_DIRECT_WIFI
  // Self-loop POST every 10s so the isolated D1 can be verified end-to-end.
  if (wifiReady && millis() - lastSelfPost > 10000) {
    lastSelfPost = millis();
    const char *body = "hello";
    WiFiClient client;
    HTTPClient http;
    http.setTimeout(8000);
    if (http.begin(client, cfgServerUrl)) {
      http.addHeader("Content-Type", "application/octet-stream");
      int code = http.POST((uint8_t *)body, strlen(body));
      String resp = (code > 0) ? http.getString() : String("HTTP_ERR_") + code;
      http.end();
      DBG(F("SELFTEST POST -> ")); DBG(code); DBG(F(" ")); DBGln(resp);
    }
  }
#endif

  if (millis() - lastPing > 10000) {
    lastPing = millis();
    if (wifiReady) sendFrameStr(Serial1,T_PING, "");
  }

  if (!configReceived && millis() - lastHeartbeat > 3000) {
    lastHeartbeat = millis();
    sendFrameStr(Serial1,T_STATUS, "WAIT_CONFIG");
  }

  if (wifiReady && WiFi.status() != WL_CONNECTED) {
    wifiReady = false;
    DBGln(F("WiFi lost"));
    sendFrameStr(Serial1,T_STATUS, "WIFI_LOST");
  }
}
