#!/usr/bin/env python3
# tools/gen_test_creds.py — generate d1_mini_relay/test_creds.h from ~/.d1_test_pass.
#
# Reads the credential file (port/ssid/pass/url) and writes a C header with
# #define TEST_SSID / TEST_PASS / TEST_SERVER_URL as string literals, so the
# sketch can be built with just `-DTEST_DIRECT_WIFI` and NO string macros on
# the command line. This sidesteps the PowerShell / arduino-cli quoting hell
# where -DTEST_SSID="x" loses its quotes before reaching gcc.
#
# The generated header is git-ignored and must NEVER be committed. The cred
# file itself is local (~/.d1_test_pass). Secrets never enter the shell
# history, the command line, or any Claude context.
#
# Usage:  python tools/gen_test_creds.py
#         (writes d1_mini_relay/test_creds.h next to the sketch)
import sys, os, pathlib

CRED_FILE = os.path.join(os.path.expanduser("~"), ".d1_test_pass")
REPO      = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
# All sketches that #include "test_creds.h" — get a local copy so Arduino's
# build (which copies the sketch to a temp dir) always resolves the include.
OUT_DIRS  = ["d1_mini_relay", "d1_wifi_test"]

def load(path):
    creds = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            kv = line.split("=", 1)
            if len(kv) != 2:
                continue
            creds[kv[0].strip().lower()] = kv[1].strip()
    return creds

def c_string(s):
    # Minimal C string escape: backslash and double-quote.
    return s.replace("\\", "\\\\").replace('"', '\\"')

def main():
    if not os.path.isfile(CRED_FILE):
        sys.exit(f"cred file not found: {CRED_FILE}")
    creds = load(CRED_FILE)
    ssid = creds.get("ssid", "")
    pw   = creds.get("pass", "")
    url  = creds.get("url", "")
    if not ssid or not pw or not url:
        sys.exit(f"cred file missing ssid/pass/url (got keys: {sorted(creds)})")

    header = (
        "// AUTO-GENERATED by tools/gen_test_creds.py — DO NOT COMMIT.\n"
        "// Source: ~/.d1_test_pass (local, git-ignored).\n"
        "#pragma once\n"
        f'#define TEST_SSID "{c_string(ssid)}"\n'
        f'#define TEST_PASS "{c_string(pw)}"\n'
        f'#define TEST_SERVER_URL "{c_string(url)}"\n'
    )
    for d in OUT_DIRS:
        out = pathlib.Path(REPO, d, "test_creds.h")
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(header, encoding="utf-8")
        print(f" wrote {out}")
    # Report only which fields were written + lengths — never the values.
    print(f"  TEST_SSID      len={len(ssid)}")
    print(f"  TEST_PASS      len={len(pw)}")
    print(f"  TEST_SERVER_URL len={len(url)}")

if __name__ == "__main__":
    main()